version: '2'
services:
    blogmicroservice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/BlogMicroservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=BlogMicroservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
